artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: research/data/stud.csv
  data_file: artifacts/data_ingestion/data.csv
  train_file: artifacts/data_ingestion/train.csv
  test_file: artifacts/data_ingestion/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  